//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Usuario.WCFUsuario {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFUsuario.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InserirUsuario", ReplyAction="http://tempuri.org/IService1/InserirUsuarioResponse")]
        UsuarioEntidade.UsuarioDetalhe InserirUsuario(UsuarioEntidade.UsuarioDetalhe usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AtivarUsuario", ReplyAction="http://tempuri.org/IService1/AtivarUsuarioResponse")]
        void AtivarUsuario(int IdUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AutenticarUsuario", ReplyAction="http://tempuri.org/IService1/AutenticarUsuarioResponse")]
        UsuarioEntidade.UsuarioDetalhe AutenticarUsuario(UsuarioEntidade.UsuarioDetalhe usuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Usuario.WCFUsuario.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Usuario.WCFUsuario.IService1>, Usuario.WCFUsuario.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UsuarioEntidade.UsuarioDetalhe InserirUsuario(UsuarioEntidade.UsuarioDetalhe usuario) {
            return base.Channel.InserirUsuario(usuario);
        }
        
        public void AtivarUsuario(int IdUsuario) {
            base.Channel.AtivarUsuario(IdUsuario);
        }
        
        public UsuarioEntidade.UsuarioDetalhe AutenticarUsuario(UsuarioEntidade.UsuarioDetalhe usuario) {
            return base.Channel.AutenticarUsuario(usuario);
        }
    }
}
